version: 2.1
orbs:
  node: circleci/node@2.1.0
  coveralls: coveralls/coveralls@1.0.6
jobs:
  test:
    executor:
      name: node/default
      tag: "13.9.0"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install JUnit coverage reporter
          command: npm install -D jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:coverage -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - coveralls/upload
  build_and_deploy_storybook:
    executor:
      name: node/default
      tag: "13.9.0"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy-storybook -- --ci
workflows:
  test_and_deploy_storybook:
    jobs:
      - test
      - build_and_deploy_storybook:
          filters:
            branches:
              only:
                - master
